# Generated by Django 5.2.5 on 2026-08-06 07:54

import django.db.models.deletion
import ingestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_alter_storedfile_sha256'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('source_file', models.FileField(blank=True, max_length=255, upload_to=ingestion.models.source_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('scanned_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('quarantined', 'Quarantined'), ('duplicate', 'Duplicate')], default='received', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_ingestions', to='organization.department')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion', to='documents.document')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicates', to='ingestion.ingestionrecord')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_ingestions', to=settings.AUTH_USER_MODEL)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestions', to='ingestion.scanner')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
