# Generated by Django 5.2.5 on 2026-08-04 09:05

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=documents.models.protected_upload_path)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('size', models.PositiveBigIntegerField()),
                ('media_type', models.CharField(default='application/pdf', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('quarantined', 'Quarantined')], default='draft', max_length=20)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('confidential', 'Confidential')], default='normal', max_length=20)),
                ('confidential_label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.department')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='departments',
            field=models.ManyToManyField(through='documents.DocumentDepartment', to='organization.department'),
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('quarantined', 'Quarantined')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='documents.document')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('stored_file', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='documents.storedfile')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddConstraint(
            model_name='documentdepartment',
            constraint=models.UniqueConstraint(fields=('document', 'department'), name='unique_document_department'),
        ),
        migrations.AddConstraint(
            model_name='documentdepartment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('document',), name='one_primary_department_per_document'),
        ),
        migrations.AddConstraint(
            model_name='documentmetadata',
            constraint=models.UniqueConstraint(fields=('document', 'key'), name='unique_document_metadata_key'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='unique_document_version'),
        ),
    ]
