# Generated by Django 5.2.5 on 2026-08-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='sha256',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
