# Generated by Django 5.2.5 on 2026-08-08 09:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


def index_existing_ocr_pages(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        INSERT INTO search_documentsearchpage
            (document_id, ocr_page_id, page_number, title, metadata_text, body,
             search_vector, updated_at)
        SELECT d.id, p.id, p.page_number, d.title,
               COALESCE(metadata.text, ''), p.text,
               setweight(to_tsvector('simple', COALESCE(d.title, '')), 'A') ||
               setweight(to_tsvector('simple', COALESCE(metadata.text, '')), 'B') ||
               setweight(to_tsvector('simple', COALESCE(p.text, '')), 'C'),
               CURRENT_TIMESTAMP
        FROM documents_document d
        JOIN LATERAL (
            SELECT v.id
            FROM documents_documentversion v
            WHERE v.document_id = d.id
            ORDER BY v.number DESC
            LIMIT 1
        ) latest ON TRUE
        JOIN ocr_ocrjob j ON j.version_id = latest.id AND j.status = 'succeeded'
        JOIN ocr_ocrpagetext p ON p.job_id = j.id
        LEFT JOIN LATERAL (
            SELECT string_agg(m.key || ' ' || m.value, ' ') AS text
            FROM documents_documentmetadata m
            WHERE m.document_id = d.id
        ) metadata ON TRUE
        """
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_supervisor_sensitivity'),
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSearchPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('metadata_text', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_pages', to='documents.document')),
                ('ocr_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_entry', to='ocr.ocrpagetext')),
            ],
            options={
                'ordering': ('document_id', 'page_number'),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_page_vector_gin')],
                'constraints': [models.UniqueConstraint(fields=('document', 'page_number'), name='unique_document_search_page')],
            },
        ),
        migrations.RunPython(index_existing_ocr_pages, migrations.RunPython.noop),
    ]
