# Generated by Django 5.2.5 on 2026-08-07 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_supervisor_sensitivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('embedded_text', 'Existing PDF text'), ('ocr', 'Optical character recognition')], max_length=20)),
                ('languages', models.CharField(default='eng+fra+ara', max_length=100)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('warning', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('searchable_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocr_derivatives', to='documents.storedfile')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_job', to='documents.documentversion')),
            ],
        ),
        migrations.CreateModel(
            name='OcrPageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr.ocrjob')),
            ],
            options={
                'ordering': ('page_number',),
                'constraints': [models.UniqueConstraint(fields=('job', 'page_number'), name='unique_ocr_job_page')],
            },
        ),
    ]
